### ISSUE TITLE
Any ways to add some extra extensions ?

### ISSUE THREAD

**Issue by apsylone** [phpmentors-jp/docker-images#23]
Hi Mentors :-)

I would like to know if there is any ways to add some extras PHP5 extensions ?
In my case, I would like to add _memcached_.

Thanks for your anwser :-)

**Comment by iteman** [comment]
The `APP_INIT` environment variable can be used for this.

First, write a script as the following:

`docker/app-init`:

```bash
#!/bin/bash

apt-get update
apt-get -y upgrade

apt-get -y install php5-gd
RETVAL=$?
if [ $RETVAL -ne 0 ]; then
   exit $RETVAL
fi

...
```

Second, specify the script as the value of the `APP_INIT_SCRIPT` environment variable as the following:

`docker-compose.yml`:

```yaml
version: '2'
services:
    app:
        image: "phpmentors/symfony-app:php55"
        ...
        environment:
            APP_INIT_SCRIPT: "docker/app-init"
        ...
```

If the value of the `APP_INIT_SCRIPT` environment variable is relative path, `/var/app` will be added to the beginning of the value.
